"""
Django settings for trazabilidad_project project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--x@%vf@@6i7-*ib6kz2w*$(qu7!yl(h#dd6usf5ka!1oed)my9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
# FASE 1 - Setup & Configuración DRF: apps de terceros necesarias para
# serialización, filtrado, documentación OpenAPI y CORS.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'rest_framework',
    'django_filters',
    'corsheaders',
    'drf_spectacular',

    # App propia
    'lotes',
]

# FASE 1 - CORS debe ir lo más arriba posible en el middleware (antes de
# CommonMiddleware) para poder añadir las cabeceras Access-Control-* a toda
# respuesta, incluidas las de error.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trazabilidad_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trazabilidad_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# FASE 1 - Configuración centralizada de Django REST Framework
# Regla: prohibido hardcodear permisos en las vistas; se define aquí el
# comportamiento por defecto y solo se sobrescribe cuando es estrictamente
# necesario (ver @action en lotes/views.py).
# =============================================================================
REST_FRAMEWORK = {
    # FASE 3 - permisos por defecto: lectura pública, escritura autenticada
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],

    # FASE 4 - Paginación estándar (evita MemoryError en datasets grandes)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,

    # FASE 4 - Filtrado por query params (DjangoFilterBackend), búsqueda y orden
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # FASE 4 - Throttling: protección contra scraping/abuso
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '60/minute',
        # Throttle personalizado para el endpoint sensible de reporte (Fase 3)
        'reporte': '5/minute',
    },

    # FASE 5 - Documentación OpenAPI/Swagger automática con drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Trazabilidad Forestal - BioTrace Labs',
    'DESCRIPTION': (
        'API RESTful production-ready para el registro y seguimiento de '
        'lotes forestales (Semana 12/13 - IS093A). Implementa serialización '
        'avanzada, ViewSets + Routers, paginación, filtrado, throttling, '
        'CORS/CSRF y estilo HATEOAS.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# =============================================================================
# FASE 5 - CORS: permitir orígenes específicos del frontend SPA (no usar '*'
# en producción). Ajustar según el puerto real del frontend (Vite/React/Vue).
# =============================================================================
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',   # Vite dev server
]
CORS_ALLOW_CREDENTIALS = True  # necesario si el SPA envía cookies de sesión

# FASE 5 - CSRF: dominios de confianza para peticiones AJAX/SPA autenticadas
# por sesión. El frontend debe leer la cookie 'csrftoken' y enviarla en la
# cabecera X-CSRFToken en cada POST/PUT/PATCH/DELETE.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
]
