# Generated by Django 5.2.15 on 2026-07-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteForestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('especie', models.CharField(max_length=100)),
                ('origen', models.CharField(help_text='Zona / concesion forestal de origen', max_length=150)),
                ('cantidad_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('en_transito', 'En tránsito'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='registrado', max_length=20)),
                ('costo_interno', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
